version: "3"

services:
  db:
    container_name: postgresql-audit
    image: postgres
    volumes:
      ## Audit Function
      - ./db_init/audit_column_to_query.sql:/docker-entrypoint-initdb.d/audit_column_to_query.sql
      - ./db_init/audit_get_table_columns.sql:/docker-entrypoint-initdb.d/audit_get_table_columns.sql
      - ./db_init/audit_table_column_added.sql:/docker-entrypoint-initdb.d/audit_table_column_added.sql
      - ./db_init/audit_table_column_updated.sql:/docker-entrypoint-initdb.d/audit_table_column_updated.sql
      - ./db_init/audit_table_copy.sql:/docker-entrypoint-initdb.d/audit_table_copy.sql
      - ./db_init/audit_table_triggers.sql:/docker-entrypoint-initdb.d/audit_table_triggers.sql
      - ./db_init/audit_table.sql:/docker-entrypoint-initdb.d/audit_table.sql
      - ./db_init/audit_schema.sql:/docker-entrypoint-initdb.d/audit_schema.sql
      - ./db_init/audit_db.sql:/docker-entrypoint-initdb.d/audit_db.sql
      ## Test Data
      - ./test/create_db_audit.sql:/docker-entrypoint-initdb.d/create_db_audit.sql
      - ./test/base.sql:/docker-entrypoint-initdb.d/base.sql
      - ./test/copy_fn_to_audit.sql:/docker-entrypoint-initdb.d/copy_fn_to_audit.sql
      - ./test/test_add_column.sql:/docker-entrypoint-initdb.d/test_add_column.sql
      - ./test/test_alter_column.sql:/docker-entrypoint-initdb.d/test_alter_column.sql
      - ./test/test_audit_insert.sql:/docker-entrypoint-initdb.d/test_audit_insert.sql
      - ./test/audit_run_tests.sql:/docker-entrypoint-initdb.d/audit_run_tests.sql
    environment:
      POSTGRES_USER: db_user
      POSTGRES_DB: example_db
      POSTGRES_PASSWORD: 1234
    ports:
      - 5433:5432