version: "3"

services:
  db:
    container_name: postgresql-audit
    image: postgres
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: db_user
      POSTGRES_DB: example_db
      POSTGRES_PASSWORD: 1234
    ports:
      - 5433:5432