version: 2
jobs:
  build:

    # Primary container image where all commands run

    docker:
      - image: circleci/python:3.6.2-stretch-browsers
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
        environment:
          TEST_DATABASE_URL: postgresql://root@localhost/circle_test

    # Service container image

      - image: circleci/postgres:9.6.5-alpine-ram
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference

    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install postgresql-client-9.6
      - run: whoami
      - run: |
          ls
          pwd
          psql \
            -d $TEST_DATABASE_URL \
            -c "CREATE DATABASE audit;"
          psql \
            -d $TEST_DATABASE_URL \
            -c "CREATE EXTENSION dblink;"
          psql \
            -d $TEST_DATABASE_URL \
            -c "CREATE TYPE example_enum AS ENUM('left', 'right');"
          psql \
          -d $TEST_DATABASE_URL \
          -c "CREATE TABLE "lang" ( "id" varchar NOT NULL, "name" varchar NOT NULL, "localname" varchar NOT NULL, "active" boolean NOT NULL DEFAULT FALSE, "is_blocked" boolean NOT NULL DEFAULT FALSE, "created_by" integer, "updated_by" integer, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP, "type" example_enum, CONSTRAINT "UQ_id_lang" UNIQUE ("id"), CONSTRAINT "PK_id_lang" PRIMARY KEY ("id") );"
          psql \
          -d $TEST_DATABASE_URL \
          -c "SELECT test_audit();"