version: 2
jobs:
  build:
    docker:
      - image: circleci/postgres:9.6-alpine
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
        environment:
          POSTGRES_USER: db_user
          POSTGRES_DB: example_db
          POSTGRES_PASSWORD: 1234

    steps:
      - checkout
      - run:
          name: Test number 2 -> ?
          command: |
            psql \
            -d $TEST_DATABASE_URL \
            -c "CREATE DATABASE audit;"
            -c "SELECT test_audit();"
workflows:
  version: 2
  build-deploy:
    jobs:
      - build